/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioView: typeof import('./src/components/AudioView.vue')['default']
    ClickMove: typeof import('./src/components/ClickMove.vue')['default']
    Code: typeof import('./src/components/icons/Code.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    Feiniu: typeof import('./src/components/icons/Feiniu.vue')['default']
    FileView: typeof import('./src/components/FileView.vue')['default']
    ImageView: typeof import('./src/components/ImageView.vue')['default']
    Iso: typeof import('./src/components/icons/Iso.vue')['default']
    MdView: typeof import('./src/components/MdView.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    OfficeExcel: typeof import('./src/components/icons/OfficeExcel.vue')['default']
    OfficePPT: typeof import('./src/components/icons/OfficePPT.vue')['default']
    OfficeWord: typeof import('./src/components/icons/OfficeWord.vue')['default']
    Pdf: typeof import('./src/components/icons/Pdf.vue')['default']
    PdfView: typeof import('./src/components/PdfView.vue')['default']
    VideoView: typeof import('./src/components/VideoView.vue')['default']
    Zip: typeof import('./src/components/icons/Zip.vue')['default']
  }
}

// For TSX support
declare global {
  const AudioView: typeof import('./src/components/AudioView.vue')['default']
  const ClickMove: typeof import('./src/components/ClickMove.vue')['default']
  const Code: typeof import('./src/components/icons/Code.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ElTree: typeof import('element-plus/es')['ElTree']
  const Feiniu: typeof import('./src/components/icons/Feiniu.vue')['default']
  const FileView: typeof import('./src/components/FileView.vue')['default']
  const ImageView: typeof import('./src/components/ImageView.vue')['default']
  const Iso: typeof import('./src/components/icons/Iso.vue')['default']
  const MdView: typeof import('./src/components/MdView.vue')['default']
  const MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
  const OfficeExcel: typeof import('./src/components/icons/OfficeExcel.vue')['default']
  const OfficePPT: typeof import('./src/components/icons/OfficePPT.vue')['default']
  const OfficeWord: typeof import('./src/components/icons/OfficeWord.vue')['default']
  const Pdf: typeof import('./src/components/icons/Pdf.vue')['default']
  const PdfView: typeof import('./src/components/PdfView.vue')['default']
  const VideoView: typeof import('./src/components/VideoView.vue')['default']
  const Zip: typeof import('./src/components/icons/Zip.vue')['default']
}